---
secretStore:
  name: vault-backend
  kind: ClusterSecretStore

bucketSecrets:
  - localdocs

s3:
  default_endpoint: http://minio-service.minio-ns.svc.cluster.local:9000
  default_region: none

pipeline:
  default_host: minio-service.minio-ns.svc.cluster.local:9000
  scheme: http
  bucket: pipelines