apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  finalizers:
  - datasciencepipelinesapplications.opendatahub.io/finalizer
  name: dspa
spec:
  apiServer:
    applyTektonCustomResource: true
    archiveLogs: false
    artifactSignedURLExpirySeconds: 60
    autoUpdatePipelineDefaultVersion: true
    caBundleFileMountPath: ""
    caBundleFileName: ""
    collectMetrics: true
    dbConfigConMaxLifetimeSec: 120
    deploy: true
    enableOauth: true
    enableSamplePipeline: false
    injectDefaultScript: true
    stripEOF: true
    terminateStatus: Cancelled
    trackArtifacts: true
  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  dspVersion: v2
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    externalStorage:
      basePath: ""
      bucket: {{ $.Values.pipeline.bucket }}
      host: {{ $.Values.pipeline.default_host }}
      port: {{ $.Values.pipeline.port }}
      region: no-region
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: dashboard-dspa-secret
      scheme: {{ $.Values.pipeline.scheme }}
  persistenceAgent:
    deploy: true
    numWorkers: 2
  podToPodTLS: true
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true